import { typeKeys } from "../interfaces";

export const keys: typeKeys = {
    Q: { status: "empty" },
    W: { status: "empty" },
    E: { status: "empty" },
    R: { status: "empty" },
    T: { status: "empty" },
    Y: { status: "empty" },
    U: { status: "empty" },
    I: { status: "empty" },
    O: { status: "empty" },
    P: { status: "empty" },
    A: { status: "empty" },
    S: { status: "empty" },
    D: { status: "empty" },
    F: { status: "empty" },
    G: { status: "empty" },
    H: { status: "empty" },
    J: { status: "empty" },
    K: { status: "empty" },
    L: { status: "empty" },
    Z: { status: "empty" },
    X: { status: "empty" },
    C: { status: "empty" },
    V: { status: "empty" },
    B: { status: "empty" },
    N: { status: "empty" },
    M: { status: "empty" },
    Ñ: { status: "empty" },
};
